window.storyContent = {
    inkVersion: 21,
    root: [
        [{ "->": "start" }, ["done", { "#n": "g-0" }], null],
        "done",
        {
            start: [
                [
                    "^<h1> Potato Peace </h1>",
                    "\n",
                    "^<br/>",
                    "\n",
                    "ev",
                    "str",
                    "^Start Game",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    "ev",
                    "str",
                    "^About",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 4 },
                    "ev",
                    "str",
                    "^Help",
                    "/str",
                    "/ev",
                    { "*": ".^.c-2", flg: 4 },
                    {
                        "c-0": ["^ ", { "->": "intro" }, "\n", null],
                        "c-1": ["^ ", { "->": "about" }, "\n", null],
                        "c-2": ["^ ", { "->": "help" }, "\n", null]
                    }
                ],
                null
            ],
            about: [
                [
                    "^Potato Peace is a whimsical visual novel that combines elements of comedy, mystery, and diplomacy into a delightful potato-filled adventure.",
                    "\n",
                    "^Created by ronynn, a passionate potato enthusiast, Potato Peace aims to entertain and delight players with its charming characters, quirky humor, and heartwarming story.",
                    "\n",
                    "^Potato Peace is a celebration of multiculturalism and the power of forging one's own path in a diverse world.",
                    "\n",
                    "^Set in the bustling streets of Spudopolis, where humans and potatoes live side by side, the game explores themes of unity, diversity, and the importance of embracing one's unique identity.",
                    "\n",
                    "^So grab your potato-themed snacks and get ready to embark on an adventure that celebrates the diversity of the human (and potato) experience!",
                    "\n",
                    "ev",
                    "str",
                    "^Go Back",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    { "c-0": ["^ ", { "->": "start" }, "\n", null] }
                ],
                null
            ],
            help: [
                [
                    "^Touch or click anywhere on the screen to progress through the story, game ending choices only appear near the very end.",
                    "\n",
                    "^Mostly it's a linear game until the end, there are two sections where one choice makes you skip the other.",
                    "\n",
                    "^UI buttons are potato themed.",
                    "\n",
                    "^First one is for saving or loading a specfic save state of the game.",
                    "\n",
                    "^Second one is for changing theme of the game screen to day or night.",
                    "\n",
                    "^Third one is to see a transcript of the game as you have played.",
                    "\n",
                    "^Fourth one is the restart button, that you will not be needing until the very end.",
                    "\n",
                    "ev",
                    "str",
                    "^Go Back",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    { "c-0": ["^ ", { "->": "start" }, "\n", null] }
                ],
                null
            ],
            intro: [
                [
                    "^Narrator: Humans and potatoes have coexisted peacefully for generations. ",
                    "#",
                    "^img bg: cover.png",
                    "/#",
                    "\n",
                    "^Potatoes possess intelligence and emotions, forming their own societies alongside humans.",
                    "\n",
                    "^In the bustling city of Spudopolis, tensions between the two species are on the rise.   ",
                    "#",
                    "^img bg: cover.png",
                    "/#",
                    "\n",
                    "^Your father was a diplomat tasked with maintaining the delicate peace between humans and potatoes.",
                    "\n",
                    "^As tensions boiled like a pot of mashed potatoes about to bubble over, mysterious incidents threatened to turn Spudopolis into a salad of chaos.",
                    "\n",
                    "^But your old man always managed to peel away the layers of conflict and keep the peace.",
                    "\n",
                    "^Things were much calmer when you took on the same job, following in his footsteps. ",
                    "#",
                    "^img bg: town.png",
                    "/#",
                    "\n",
                    "^You took the job, determined to keep your town as cool as a cucumber... err, potato.",
                    "\n",
                    "^However, when the pie of peace — a symbolic statue of a potato holding a pie—goes missing, you give it your all to find the statue and the culprit, but end up with as many leads as a potato has legs. ",
                    "#",
                    "^img statue: statue.png 90 100 60",
                    "/#",
                    "\n",
                    "^With your reputation mashed and pressure from your seniors piling up like a mountain of fries, you decide to take an early retirement and settle in a cozy cabin near the woods, hoping to escape the heat and maybe fry up some new ideas. ",
                    "#",
                    "^img bg: woods.png",
                    "/#",
                    "\n",
                    "^But just when you thought you could finally catch a break, your past comes knocking at your door like a delivery truck. ",
                    "#",
                    "^img statue:",
                    "/#",
                    "\n",
                    "^What some might call a happy reunion, you call a potential disaster. You didn't start living in the woods to host impromptu parties, after all. ",
                    "#",
                    "^img mc: mc.png 50 100 50",
                    "/#",
                    "\n",
                    "^During your investigations, you uncovered enough evidence to fill a sack of potatoes, all pointing to the mayor's shady connections with certain organizations who seem bent on disrupting the potato peace.",
                    "\n",
                    "^Sure, as mayor, he may have had to rub elbows with them for political reasons, but he's always been on your suspect list, and today he's at your doorstep, sizzling with suspicion.",
                    "\n",
                    "^You decided to just not open the door.",
                    "\n",
                    "ev",
                    "str",
                    "^Pretend to be asleep.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "door1" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            door1: [
                [
                    "^It's been three minutes and he isn't going anywhere,",
                    "\n",
                    '^<div class="door-knocking">and he has already started knocking harder. </div>',
                    "\n",
                    "^Why don't people call first!  ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    "ev",
                    "str",
                    "^Open the door and greet him with a smile.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    "ev",
                    "str",
                    '^"Open the door and throw some tomato sauce on him, pretend you thought it was a friend who pranks you everyday. " ',
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 4 },
                    {
                        "c-0": ["^ ", { "->": "door" }, "\n", null],
                        "c-1": ["^ ", { "->": "do" }, "\n", null]
                    }
                ],
                null
            ],
            do: [
                "^You can't help but be tempted by the mischievous voice in your head. With a devilish grin, you grab the nearest bottle of tomato sauce and fling open the door, splattering the startled mayor with a generous dollop.",
                "\n",
                '^"Oops, my bad!" you exclaim, barely able to contain your laughter. "I thought you were my friend, Larry. He\'s always pulling pranks like this. Come on in and I\'ll grab you a towel."',
                "\n",
                "^With a neutral expression he stares at his white suit now covered in tomato sauce.",
                "\n",
                "^He then calmy greets you and tells you not to worry about the suit. ",
                { "->": "door" },
                "\n",
                null
            ],
            door: [
                [
                    '^You take a deep breath and put on your best smile before swinging open the door. "Well, hello there, Mayor Russet! What a pleasant surprise," you chirp, trying to sound as cheerful as possible.',
                    "\n",
                    "^Despite your suspicions, you never found enough proof against him. He might just be the rarest of creatures: an honest politician with no ulterior motives. ",
                    "#",
                    "^img mayor: mayor.png 100 100 40",
                    "/#",
                    "\n",
                    "^\"Thought I'd say hi,\" the mayor greets you with a smile as wide as a politician's promises. You smile back and nod, trying to hide your uneasiness.",
                    "\n",
                    '^"I was just setting up the table for dinner. Why don\'t you take a seat?" you offer.',
                    "\n",
                    '^"Sure," the mayor replies, settling into the chair with the confidence of a man who knows where all the skeletons are buried. Panic washes over you like a sudden rainstorm as you realize you only prepared enough food for one—yourself.',
                    "\n",
                    "^Your smile tightens as you try to hide your anxiety, but it's about as effective as a leaky boat in a storm.",
                    "\n",
                    "^\"I hope you don't mind my uninvited presence here. You see, there's something very important I have to say to you...\" the mayor begins, before you cut him off with a desperate attempt at diversion.",
                    "\n",
                    '^"Would you like some soup?" you interject, hoping to steer the conversation away from whatever political landmine he\'s about to drop.',
                    "\n",
                    '^"Yeah, sure. See, umm, let me get back to where I was... Umm... Where was I...?" the mayor stammers, clearly thrown off course by your culinary intervention.',
                    "\n",
                    "ev",
                    "str",
                    "^Bring him back to the point",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Distract and get him out of the house",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": [
                            "^ You gesture emphatically, trying to steer him back on track. ",
                            { "->": "house" },
                            "\n",
                            { "#f": 5 }
                        ],
                        "c-1": [
                            "^ You scramble for a distraction, but your mind draws a blank. ",
                            { "->": "house" },
                            "\n",
                            { "#f": 5 }
                        ]
                    }
                ],
                null
            ],
            house: [
                [
                    '^"Oh yes! I remember," the mayor suddenly blurts out, causing you to jump. "It was me! That\'s what I\'ve been dying to tell you all these years, but I just couldn\'t bring myself to say it."',
                    "\n",
                    '^He pauses dramatically, staring at your face like he\'s waiting for your reaction. "I was the one who arranged for the statue to be placed elsewhere, the great Pie of Peace. I have it."',
                    "\n",
                    "^The revelation hits you like a ton of bricks, and your hands start trembling uncontrollably. The mayor notices, of course.",
                    "\n",
                    '^"The mayor notices your hands trembling," he says matter-of-factly, as if narrating his own movie.',
                    "\n",
                    '^"Look, I honestly thought you\'d be able to solve the case yourself," the mayor continues after a slow chuckle, completely unfazed by your shock.',
                    "\n",
                    '^"But it seems this wasn\'t the kind of job for you. I honestly never understood why you would leave your job over something like this."',
                    "\n",
                    '^He puts a hand on your trembling fingers, his touch surprisingly comforting. "I want to work with you again.',
                    "\n",
                    '^I want you to announce that you finally found the culprit, get some rewards, and then get back to work."',
                    "\n",
                    '^He leans in closer, his voice dropping to a whisper. "The mayor\'s house is where the statue was always meant to stay, since I am the one who displaced it, it never really mattered."',
                    "\n",
                    '^"What!" you finally manage to sputter, but before you can protest further, the mayor shushes you with a finger to your lips.',
                    "\n",
                    '^"I don\'t want you to be upset," he says soothingly. "I misplaced it, thought it got stolen.',
                    "\n",
                    "^Now it's been found, and I want you back at your job. You're the best diplomat I had.\"",
                    "\n",
                    "^With that, the mayor gets up and approaches the door, leaving you speechless and still trembling. \"I believe I'll be seeing you at the ceremony I'm throwing for your return at the town hall,\" he says with a chuckle as he opens the door,",
                    "\n",
                    "^... revealing his hands still covered in soup from your earlier distraction.",
                    "\n",
                    "^As the door closes behind him, you sink into your chair, trying to process everything that just happened. ",
                    "#",
                    "^img mayor:",
                    "/#",
                    "\n",
                    "^You can't help but think back to the day the stolen statue was first reported to you.",
                    "\n",
                    "^Taking a deep breath, you steel yourself for what comes next. It's time to step out into the bustling streets of Spudopolis and confront the mysteries that brought you here in the first place. ",
                    "#",
                    "^img bg: town.png",
                    "/#",
                    "\n",
                    "^The air is tense with anticipation, whispers of unrest circulating among the potato and human inhabitants alike.",
                    "\n",
                    "^As a junior diplomat, it's your duty to investigate the robbery of the statue of the Pie of Peace, made by a prominent potato activist, and prevent further escalation of hostilities. ",
                    "#",
                    "^img mc: mc2.png 50 100 60",
                    "/#",
                    "\n",
                    "^Where do you begin?",
                    "\n",
                    "ev",
                    "str",
                    "^Review the evidence at the crime scene.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "review" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            community: [
                [
                    "^You visit the potato enclave on the outskirts of Spudopolis, where the activist once rallied support for potato rights. A group of spuds gathers around you, eyeing you warily. ",
                    "#",
                    "^img bg: town.png",
                    "/#",
                    "\n",
                    '^You approach a cluster of potatoes huddled near the entrance of a potato-run cafe. "Excuse me," you begin, "I\'m investigating a stolen statue from the Mayor\'s house. Did anyone here see anything unusual?" ',
                    "#",
                    "^img mc: mc2.png 50 100 60",
                    "/#",
                    "\n",
                    "ev",
                    "str",
                    "^Inquire about any suspicious characters in the area.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "susp" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            susp: [
                [
                    '^The potatoes exchange glances, then one speaks up. "Well, I did see a potato rolling away suspiciously fast yesterday..."',
                    "\n",
                    "ev",
                    "str",
                    "^Follow up on the potato's tip.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Thank the potatoes and contemplate your next move.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["^ ", { "->": "tip" }, "\n", { "#f": 5 }],
                        "c-1": ["^ ", { "->": "Thank" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            tip: [
                [
                    "^You walk around further into the alley, you see nothing of importance, no cameras anywhere, this was a waste of time.",
                    "\n",
                    "^You come back where you were, the potatoes are still around the cafe area, glancing at you, you don't have much to ask from them anymore.",
                    "\n",
                    "ev",
                    "str",
                    "^Thank the potatoes and contemplate your next move.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "Thank" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            Thank: [
                [
                    "^You knock on the door of Mrs. Murphy, the creator of the Peace of Pie statue, also known for her activism and award-winning sculptures. ",
                    "#",
                    "^img bg: sculptor.png",
                    "/#",
                    "\n",
                    '^"Hello?" you say, opening the door a crack. "I\'m investigating a pie-napping. Mind if I ask you a few questions?"',
                    "\n",
                    '^Mrs. Murphy\'s eyes widen in horror. "A pie-napping? But who would steal my precious pies?!"',
                    "\n",
                    "^\"Well, the Pie of Peace statue that you gifted the town was recently stolen, and if you don't mind, I'd like to check your house.\"",
                    "\n",
                    '^"HELL NO!" she replies, her voice echoing through the neighborhood. "You ain\'t coming into my house, my property. I was going to invite you in for some snacks, but hell no, get off my porch."',
                    "\n",
                    "^You try to manage the situation, talking about how much the statue means to you, but you only manage to dig yourself deeper into the pie crust of awkwardness.",
                    "\n",
                    "ev",
                    "str",
                    "^Ask her to make a replacement statue while you investigate.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    {
                        "c-0": [
                            "^ ",
                            { "->": "replacement" },
                            "\n",
                            { "#f": 5 }
                        ]
                    }
                ],
                null
            ],
            replacement: [
                [
                    '^"What?" asks Mrs. Murphy, looking utterly confused. "You one weird fellow. Go get some sleep; you\'re talking crazy."',
                    "\n",
                    "^This was the moment that spelled doom for you. You kept insisting that you have sufficient reasons to get her house searched for the statue, but the statue was still never found, ruining your reputation and that of your department.  ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    "^Detectives stopped asking assessments of diplomats in human-potato conflicts, and this incident placed you in your wood cabin. ",
                    "#",
                    "^img bg: woods.png",
                    "/#",
                    "\n",
                    "^But the story of your life has turned a new page. With the statue found, you can claim your position back, and perhaps someday you will be a successful diplomat like your dad. ",
                    "#",
                    "^img statue: statue.png 90 100 60",
                    "/#",
                    "\n",
                    "^You are now at the ceremony, entirely being conducted to celebrate your comeback, while the statue is being put back in its place. ",
                    "#",
                    "^img bg: ceremony.png",
                    "/#",
                    "\n",
                    "^You have finally cracked the case wide open! But you decide not to take the credit. ",
                    "#",
                    "^img statue:",
                    "/#",
                    "\n",
                    '^"It was Mr. Russet who found the statue. I wouldn\'t be here without his personal efforts." ',
                    "#",
                    "^img mc: mc3.png 100 100 40",
                    "/#",
                    "\n",
                    "^The mayor gives you an expressionless grin.",
                    "\n",
                    "^\"Turns out, the pie thief was none other than our beloved Mayor, who couldn't resist the allure of Mrs. Murphy's famous pies,\" reads the headlines, the incident being a fun historical event for the town. ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    '^As you enjoy a celebratory slice of pie with some of your old colleagues, Mayor Russet saunters into your view with a smug grin. "Congratulations on solving the case," he says, his voice dripping with insincerity. "A job well done, indeed." ',
                    "#",
                    "^img mayor: mayor.png 100 100 40",
                    "/#",
                    "\n",
                    "ev",
                    "str",
                    "^Accept the mayor's praise with a wary eye.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "Accept" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            Accept: [
                [
                    "^As the festivities continue, you can't shake the feeling that something sinister is afoot. Could Mayor Russet have his own agenda?",
                    "\n",
                    "^Mayor Russet steps forward grabbing your hand and bringing you to the stage, his presence commanding the attention of the entire town.",
                    "\n",
                    '^"My dear citizens of Spudopolis," he begins, his voice booming with authority. "Today, we celebrate the resolution of a petty crime.',
                    "\n",
                    '^But what if I were to tell you that this crime was not just an isolated incident, but a deliberate revolution that we must bring together?"',
                    "\n",
                    "^The crowd murmurs in confusion, casting wary glances at one another. Mayor Russet's eyes gleam with triumph as he continues his monologue. ",
                    "#",
                    "^img mayor: mayor.png 100 100 50",
                    "/#",
                    "\n",
                    '^"By stealing the pie, which symbolized the peace between our two communities, I instilled a seed of fear in your hearts.',
                    "\n",
                    "^The society we live in today is nothing but a cynical veil, and no peace can be achieved in a world, where we still have to hide our true feelings.",
                    "\n",
                    "^If one can rise up and take away the symbol of this make belief peace, they others will rise too, or so I thought.",
                    "\n",
                    '^What I brought forward was an idea, but ideas are useless without people backing them, and I plan to bring forward the very revolution we all wish for."',
                    "\n",
                    "^Gasps fill the air as Mayor Russet reveals his true intentions, his words ringing with a chilling certainty.",
                    "\n",
                    '^"Peace was never an option," he declares boldly.',
                    "\n",
                    '^"And now, it\'s time for us to embrace a new era—one of conflict, dominance, and potato supremacy!"',
                    "\n",
                    "^The fate of Spudopolis hangs in the balance as Mayor Russet's grand scheme unfolds. ",
                    "#",
                    "^img mayor:",
                    "/#",
                    "\n",
                    "^Will you stand idly by and watch as chaos reigns, or will you rise up and fight for the peace and harmony that once united humans and potatoes alike?",
                    "\n",
                    "ev",
                    "str",
                    "^Attempt to intervene and debate the Mayor.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Rally the town against the mayor's tyranny.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["^ ", { "->": "debate" }, "\n", { "#f": 5 }],
                        "c-1": ["^ ", { "->": "Rally" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            debate: [
                [
                    "^You step forward, determined to challenge Mayor Russet's dangerous rhetoric. ",
                    "#",
                    "^img mc: mc3.png 100 100 40",
                    "/#",
                    "\n",
                    '^"Mayor Russet," you begin, your voice steady despite the tension in the air.',
                    "\n",
                    '^"Your plan to incite conflict and division among us is reckless and misguided.',
                    "\n",
                    '^Peace and unity are the foundation of our community, and I will not stand idly by while you tear it apart."',
                    "\n",
                    "^The crowd watches with bated breath as you and Mayor Russet engage in a heated debate, exchanging arguments and counterarguments with fervor.",
                    "\n",
                    "^With each compelling point you make, you can see doubt creeping into the minds of the townsfolk, their allegiance wavering.",
                    "\n",
                    "ev",
                    "str",
                    "^Continue to argue your case, using logic and reason.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Appeal to the townsfolk's sense of empathy and compassion.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["^ ", { "->": "logic" }, "\n", { "#f": 5 }],
                        "c-1": ["^ ", { "->": "compassion" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            Rally: [
                [
                    "^You stand before the gathered crowd, your heart pounding with determination.",
                    "\n",
                    '^"My fellow citizens," you begin, your voice ringing out with conviction. ',
                    "#",
                    "^img mc: mc3.png 100 100 40",
                    "/#",
                    "\n",
                    '^"We stand at a crossroads—a choice between succumbing to fear and division, or standing together in solidarity against tyranny."',
                    "\n",
                    "^With each word you speak, you can feel the energy of the crowd swelling, their eyes alight with hope and determination.",
                    "\n",
                    "^You paint a vivid picture of a future where humans and potatoes coexist in harmony, where differences are celebrated rather than feared.",
                    "\n",
                    "ev",
                    "str",
                    "^Appeal to the townsfolk's sense of empathy and compassion.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "compassion" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            logic: [
                [
                    "^You press on, dismantling Mayor Russet's dangerous ideology with airtight arguments and indisputable facts.",
                    "\n",
                    "^With each point you make, the crowd's skepticism towards the mayor's plans grows, their support for your cause strengthening, or so you thought.",
                    "\n",
                    "^As you lay out the flaws in the mayor's logic and highlight the benefits of peace and unity, you can see doubt flickering in people's eyes, unable to understand political terminology and philosophical rhetoric, ...",
                    "\n",
                    "^... the sudden realisation makes you stutter, the opportunity Mr. Russet was waiting for. ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    "^Mayor Russet stares at the town, after a brief pause he speaks, ",
                    "#",
                    "^img mayor: mayor.png 100 100 40",
                    "/#",
                    "\n",
                    '^"This woman in front of you, speaks many words to sway your attention to how much he knows about everything more than you do.',
                    "\n",
                    '^But I ask you, just this once, to believe in yourself, and in your freedom. I ask you, to stand up for me, as I stood up for you." ',
                    "#",
                    "^img mayor: mayor.png 90 100 60",
                    "/#",
                    "\n",
                    "^The crowd cheers into a roar as you get dragged off the stage, the last thing you remember before falling unconscious was the evil grin of Mayor Russet.",
                    "\n",
                    "^You succumb to your injuries and later die at the hospital. ",
                    "#",
                    "^img mayor:",
                    "/#",
                    "\n",
                    "^The End (Ending 2)",
                    "\n",
                    "ev",
                    "str",
                    "^Play again?",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    { "c-0": ["^ ", { "->": "Restart" }, "\n", null] }
                ],
                null
            ],
            Restart: ["#", "^RESTART", "/#", "end", null],
            compassion: [
                [
                    '^You shift tactics, appealing to the townsfolk\'s sense of empathy and compassion. "My friends," you implore, your voice tinged with emotion.',
                    "\n",
                    "^\"Think of the bonds we've forged, the memories we've shared. Do we want to throw it all away for the sake of petty conflicts and division?\" ",
                    "#",
                    "^img mc: mc3.png 70 100 40",
                    "/#",
                    "\n",
                    "^The crowd listens intently, their faces softening as you speak from your heart.",
                    "\n",
                    "^You share stories of unity and friendship, reminding them of the strength that comes from standing together in the face of adversity.",
                    "\n",
                    "ev",
                    "str",
                    "^Continue to tug at their heartstrings, painting a vivid picture of a future filled with love, laughter, and potato pies shared in peace.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Ask the town to kick out the mayor, urging the townsfolk to choose unity over division.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["^ ", { "->": "tug" }, "\n", { "#f": 5 }],
                        "c-1": ["^ ", { "->": "kick" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            tug: [
                [
                    "^As you paint a vivid picture of a future filled with love, laughter and potato pies shared in peace and highlight the benefits of peace and unity,",
                    "\n",
                    "^... you can see doubt flickering in people's eyes, seeing through your fiction and fake sense of security for all. The sudden realisation makes you stutter, the opportunity Mr. Russet was waiting for. ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    '^Mayor Russet stares at the town, after a brief pause he speaks, "This woman in front of you, speaks many words to sway your attention to a fake sense of reality that has never existed and will never exist. ',
                    "#",
                    "^img mayor: mayor.png 100 100 40",
                    "/#",
                    "\n",
                    '^But I ask you, just this once, to believe in yourself, and in your freedom. I ask you, to stand up for me, as I stood up for you when you needed me the most."',
                    "\n",
                    "^The crowd cheers into a roar as you get dragged off the stage, the last thing you remember before falling unconscious was the evil grin of Mayor Russet. ",
                    "#",
                    "^img mayor:",
                    "/#",
                    "\n",
                    "^You succumb to your injuries and later die at the hospital. ",
                    "#",
                    "^img mayor:",
                    "/#",
                    "\n",
                    "^The End (Ending 3)",
                    "\n",
                    "ev",
                    "str",
                    "^Play again?",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    { "c-0": ["^ ", { "->": "Restart" }, "\n", null] }
                ],
                null
            ],
            kick: [
                [
                    "^With each persuasive argument and heartfelt appeal, you succeed in swaying the hearts and minds of the townsfolk.",
                    "\n",
                    "^Mayor Russet's once-formidable influence crumbles before your eyes as the crowd rallies behind your vision of peace and unity. ",
                    "#",
                    "^img mc: mc3.png 50 100 40",
                    "/#",
                    "\n",
                    "^In a dramatic turn of events, Mayor Russet is ousted from power, his dangerous plans thwarted by the collective will of the community.",
                    "\n",
                    "^As he slinks away in defeat, you can't help but feel a sense of triumph knowing that good has prevailed over evil.",
                    "\n",
                    "^The town of Spudopolis celebrates their victory with a festive potato pie party, where humans and potatoes alike come together to share laughter, love, and delicious pie.",
                    "\n",
                    "^With the threat of conflict averted, peace and harmony are restored to Spudopolis once more.",
                    "\n",
                    "^As you bask in the warm glow of victory, surrounded by friends and allies, you can't help but feel grateful for the bonds you've forged and the lessons you've learned. ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    "^You decide that as a diplomat, you will not blindly try to follow your father's path but instead try to forge your own. ",
                    "#",
                    "^img mc: mc2.png 50 100 50",
                    "/#",
                    "\n",
                    "^And as the sun sets on another day in Spudopolis, you know that no matter what challenges may arise in the future, the power of unity and compassion will always prevail.",
                    "\n",
                    "ev",
                    "str",
                    "^The End",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 4 },
                    { "c-0": ["^ ", { "->": "GameOver" }, "\n", null] }
                ],
                null
            ],
            GameOver: [
                "^Thanks for playing Potato Peace. I would love to read your review.",
                "\n",
                "^It's my first attempt at making a visual novel, and boy, did I get myself into a pickle, I mean, potato. But hey, that's the fun of experimenting, right?",
                "\n",
                "^If you find any bugs or spelling errors, consider yourself a VIP playtester, and let me know so I can fix 'em up before the game goes live (It already has gone live hasn't it? _panics-internally_).",
                "\n",
                "^Now, go forth and spread the potato love <3!",
                "\n",
                "end",
                null
            ],
            official: [
                [
                    "^You schedule meetings with key human officials, hoping to gain insight into the political landscape of Spudopolis. ",
                    "#",
                    "^img bg: office.png",
                    "/#",
                    "\n",
                    "^While the detectives are busy finding some hobo who was paid to take the statue from the shelf, you are investigating the real masterminds who have organised this. The mayor's office is your first stop. ",
                    "#",
                    "^img mc:",
                    "/#",
                    "\n",
                    "ev",
                    "str",
                    "^Question the mayor about recent tensions.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Seek advice from a seasoned diplomat.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["^ ", { "->": "tensions" }, "\n", { "#f": 5 }],
                        "c-1": ["^ ", { "->": "seasoned" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            tensions: [
                [
                    '^You enter the grandiose office of Mayor Russet, the esteemed leader of Spudopolis. He greets you with a weary smile, his brow furrowed with concern. "Ah, young diplomat," he says, gesturing for you to take a seat. "What brings you here today?" ',
                    "#",
                    "^img mayor: mayor.png 100 100 40",
                    "/#",
                    "\n",
                    '^You cut to the chase. "I\'m investigating the statue robbery that you specifically ordered my seniors to assign me to investigate." you explain.',
                    "\n",
                    '^After some awkward silence you continue, "What can you tell me about the recent tensions between humans and potatoes?"',
                    "\n",
                    '^The mayor sighs heavily, his expression grave. "It\'s a delicate situation," he admits. "The activist was a voice for change, advocating for equality and understanding between our two communities. But not everyone shared her vision."',
                    "\n",
                    "ev",
                    "str",
                    "^Ask about potential suspects.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "sus" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            sus: [
                [
                    '^"A human, no a potato, very likely a potato did this. That\'s what you should be reporting, I mean investigating.", Mayor screams.',
                    "\n",
                    "^You walk away feeling more curious about him than you were before, specially wondering why he has so many vegetarian cook books. ",
                    "#",
                    "^img mayor:",
                    "/#",
                    "\n",
                    "ev",
                    "str",
                    "^Question the potato community.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Seek advice from a seasoned diplomat.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["^ ", { "->": "community" }, "\n", { "#f": 5 }],
                        "c-1": ["^ ", { "->": "seasoned" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            seasoned: [
                [
                    "^You set up a meeting with your dad, hoping to gain some insight and perhaps a word of appreciation from the esteemed diplomat himself.",
                    "\n",
                    "^As you sit across from him, you can't help but feel a twinge of nervousness mixed with a desperate need to impress him. ",
                    "#",
                    "^img father: father.png 0 100 60",
                    "/#",
                    "\n",
                    '^"It\'s that woman, that activist woman," your dad exclaims, his voice booming with authority.',
                    "\n",
                    '^"She did this. Trust me. This happened before. She stole the statue from the museum, saying she no longer believes potatoes and humans can live in harmony.',
                    "\n",
                    "^We wrote her a cheque to shut her up, but she's probably at her shenanigans again. Don't give her a check this time.\"",
                    "\n",
                    "^You nod eagerly, hanging on every word your dad says. After all, he's the expert in diplomatic affairs, and if anyone knows how to solve this case, it's him.",
                    "\n",
                    "^But as he continues to pontificate, you can't help but notice a certain... shall we say, flair for the dramatic in his storytelling.",
                    "\n",
                    "^You suppress a chuckle, imagining the scene of your dad chasing after an activist with a chequebook in hand, ready to buy her silence like a discount potato at the market.",
                    "\n",
                    '^"This was a good bit of information," you reply, trying to sound as professional as possible while inwardly amused by your dad\'s antics.',
                    "\n",
                    '^"If that really is the case, it would be safer to wait for her to come forward with her statements."',
                    "\n",
                    "^As you speak, you can't help but steal a glance at your dad's expression, hoping to see a glimmer of approval in his eyes.",
                    "\n",
                    "^But instead of a proud smile or a nod of acknowledgment, you're met with a stern look of concentration, as if he's mentally calculating the diplomatic repercussions of your suggestion.",
                    "\n",
                    "^You sigh inwardly, realizing that perhaps winning your dad's appreciation won't be as easy as solving a case of the missing potato statue.",
                    "\n",
                    "^But as you sit there, listening to his advice and trying to soak in every word of wisdom he imparts, you can't help but feel a sense of gratitude for the opportunity to learn from the best.",
                    "\n",
                    "^And who knows? Maybe one day, you'll solve a case so impressive that even your dad will have to admit you're a chip off the old block. ",
                    "#",
                    "^img father:",
                    "/#",
                    "\n",
                    "ev",
                    "str",
                    "^Question the potato community.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "community" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            review: [
                [
                    "^You arrive at the crime scene, a museum within the mayor's house. Investigators swarm the area like hungry seagulls at a picnic while you examine the surroundings, trying to piece together the puzzle of the missing potato statue. ",
                    "#",
                    "^img bg: museum.png",
                    "/#",
                    "\n",
                    "^Crumbs litter the ground, and there's a distinct lack of pie residue. Strange.",
                    "\n",
                    "ev",
                    "str",
                    "^Inspect the museum area for any clues.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "inspect" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            inspect: [
                [
                    '^You stumble upon a half-eaten bag of <div class="glowing-text">potato chips</div>. Could this be a clue, or just a crunchy distraction?',
                    "\n",
                    "ev",
                    "str",
                    "^Decide to snack on a few chips while you ponder your next move.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    "ev",
                    "str",
                    "^Examine the nearby surveillance footage.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-1", flg: 20 },
                    {
                        "c-0": ["\n", { "->": "chips" }, { "#f": 5 }],
                        "c-1": ["^ ", { "->": "footage" }, "\n", { "#f": 5 }]
                    }
                ],
                null
            ],
            chips: [
                [
                    '^You take a few bites from the half-eaten bag of chips, only to realize they\'re as soft as mashed potatoes. "Aha!" you shout triumphantly, crumbs flying everywhere.',
                    "\n",
                    '^"The culprit was here only a couple of hours ago, judging by the staleness of these chips. Now all we need to do is figure out who was here a couple of hours ago."',
                    "\n",
                    '^"Around what time?" a detective asks you, clearly missing the brilliance of your deduction.',
                    "\n",
                    '^"Just check the entries for the last couple of hours, Sherlock," you reply, rolling your eyes. Time is of the essence, and you don\'t have it to waste on detective work 101.',
                    "\n",
                    "ev",
                    "str",
                    "^Interview human officials.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "official" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            footage: [
                [
                    "^You decide to check the surveillance footage, hoping for a clue as obvious as a potato in a potato sack.",
                    "\n",
                    "^The cameras, however, are as useless as a fork in a soup kitchen when the museum is closed.",
                    "\n",
                    '^"Very environmentally friendly of them," you mutter sarcastically to yourself. You almost wish they had a camera just to capture the mayor\'s dramatics.',
                    "\n",
                    "^The most recent footage shows the mayor walking into view right when the museum opens.",
                    "\n",
                    "^He walks up to the area where the statue used to be, looks straight into the camera, and proceeds to put on a crying performance you'd see in a Shakespheare tragedy.",
                    "\n",
                    '^"He must have been really traumatized by this," you say to yourself, shaking your head in disbelief. It\'s almost too theatrical to be real.',
                    "\n",
                    "^With no more clues to be found here, you reluctantly move on to the next step in your investigation.",
                    "\n",
                    "ev",
                    "str",
                    "^Interview human officials.",
                    "/str",
                    "/ev",
                    { "*": ".^.c-0", flg: 20 },
                    { "c-0": ["^ ", { "->": "official" }, "\n", { "#f": 5 }] }
                ],
                null
            ],
            "global decl": [
                "ev",
                true,
                { "VAR=": "strip_speaker_tags" },
                "/ev",
                "end",
                null
            ]
        }
    ],
    listDefs: {}
};
